
services:
  dev_container:
    env_file: .env
    image: ${LOCAL_REGISTRY}/${COMPOSE_PROJECT_NAME}.dev-image:${DEV_IMAGE_BASE_REF}-${DEV_IMAGE_BASE_TAG}
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        BASE_IMAGE: ${PUBLIC_REGISTRY}/${DEV_IMAGE_BASE_REF}:${DEV_IMAGE_BASE_TAG}
    stop_grace_period: 2s
    working_dir: /workspace
    command: sh -c "rm -rf build build.debug && mkdir -p build && cmake -S . -B build; sleep infinity"
    volumes:
      - .:/workspace:z

volumes:
  dev-vscode-data: