ARG PUBLIC_REGISTRY=docker.io/library
ARG BASE_IMAGE=${PUBLIC_REGISTRY}/gcc:16
FROM ${BASE_IMAGE}

COPY <<EOF /etc/apt/sources.list.d/sid.list
deb http://deb.debian.org/debian sid main
EOF

RUN export DEBIAN_FRONTEND=noninteractive \
&&  apt -y update \
&&  apt -y --no-install-recommends install \
            cmake llvm-23 clang-23 clangd-23 lldb \
&&  update-alternatives --install  /usr/bin/clang    clang    /usr/bin/clang-23    100 \
&&  update-alternatives --install  /usr/bin/clang++  clang++  /usr/bin/clang++-23  100 \
&&  update-alternatives --install  /usr/bin/clangd   clangd   /usr/bin/clangd-23   100 \
&&  apt -y clean \
&&  rm -rf /var/lib/apt/lists/*
