ARG PUBLIC_REGISTRY=docker.io/library
ARG BASE_IMAGE=${PUBLIC_REGISTRY}/fedora:44
FROM ${BASE_IMAGE}

RUN dnf config-manager setopt fastestmirror=True max_parallel_downloads=5 install_weak_deps=False \
&&  dnf -y update \
&&  dnf -y install git gcc g++ cmake clang-tools-extra lldb \
&&  dnf clean all

CMD exit