ARG PUBLIC_REGISTRY=docker.io/library
ARG BASE_IMAGE=${PUBLIC_REGISTRY}/gcc:16
FROM ${BASE_IMAGE}

COPY <<EOF /etc/apt/sources.list.d/llvm-22.list
deb http://apt.llvm.org/trixie/ llvm-toolchain-trixie-22 main
deb-src http://apt.llvm.org/trixie/ llvm-toolchain-trixie-22 main
EOF

RUN wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key > /etc/apt/trusted.gpg.d/apt.llvm.org.asc \
&&  apt -y update \
&&  apt -y upgrade \
&&  apt -y --no-install-recommends install cmake clangd-22 lldb-22 \
&&  update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-22 100 \
&&  update-alternatives --install /usr/bin/lldb lldb /usr/bin/lldb-22 100 \
&&  update-alternatives --install /usr/bin/lldb-dap lldb-dap /usr/bin/lldb-dap-22 100 \
&&  apt -y clean \
&&  rm -rf /var/lib/apt/lists/*
